import { Router } from 'express';
import { getIncident, listIncidents, createIncident, advanceStep, resolveIncident, getIncidentReport, saveIncidentReport, signIncidentReport, createNotaDinas, incidentQueue, dutyStatus, takeIncident, assignIncident, setAwaitingPart, remindIncident, addIncidentNote, listTeknisi, inviteCollaborators, deleteIncident } from '../controllers/incidentController.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { unitScope } from '../middleware/unitScope.js';
import { withIncidentDoc } from '../middleware/upload.js';
import { validateBody } from '../middleware/validate.js';
import { createIncidentSchema } from '../schemas/index.js';

const router = Router();
router.use(requireAuth);
router.use(unitScope);
router.get('/', listIncidents);
router.get('/queue', incidentQueue);
router.get('/duty-status', dutyStatus);
router.get('/teknisi-list', listTeknisi);
router.post('/:id/collaborators', inviteCollaborators);
router.post('/', validateBody(createIncidentSchema), createIncident);
router.post('/:id/take', takeIncident);
router.post('/:id/assign', requireRole('koordinator', 'admin'), assignIncident);
router.put('/:id/awaiting-part', setAwaitingPart);
router.post('/:id/advance', withIncidentDoc, advanceStep);
router.post('/:id/remind', requireRole('koordinator', 'admin'), remindIncident);
router.post('/:id/note', addIncidentNote);
router.post('/:id/resolve', resolveIncident);
router.get('/:id', getIncident);
router.get('/:id/report', getIncidentReport);
router.put('/:id/report', saveIncidentReport);
router.post('/:id/report/sign', requireRole('koordinator', 'admin'), signIncidentReport);
router.post('/:id/nota-dinas', requireRole('koordinator', 'admin'), createNotaDinas);
router.delete('/:id', requireRole('koordinator', 'admin'), deleteIncident);

export default router;
